// <auto-generated />
using System;
using API.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(ApiDBContext))]
    [Migration("20190925083152_InitialDatabaseCreation")]
    partial class InitialDatabaseCreation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.Models.Ppg", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("greenCount1");

                    b.Property<int?>("greenCount2");

                    b.Property<int>("heartRate");

                    b.Property<float?>("hrConfidence");

                    b.Property<DateTime>("time");

                    b.Property<float?>("xAccel");

                    b.Property<float?>("yAccel");

                    b.Property<float?>("zAccel");

                    b.HasKey("id");

                    b.ToTable("ppg");
                });

            modelBuilder.Entity("API.Models.Temp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("temp");

                    b.Property<DateTime>("time");

                    b.HasKey("id");

                    b.ToTable("temp");
                });
#pragma warning restore 612, 618
        }
    }
}
